/**
 * Hand-authored types that mirror the Phase 1 schema exactly.
 * Source of truth: supabase/migrations/20260916000001_phase1_schema_auth_rls.sql
 * Naming contract:  apex_fe/.kiro/steering/naming-contract.md
 *
 * Regenerate with `supabase gen types typescript --local` once the local CLI
 * stack is running; until then this file is the authoritative type layer.
 */

// ---------------------------------------------------------------------------
// Enums
// ---------------------------------------------------------------------------

export type UserRole           = 'student' | 'consultant' | 'admin'
export type LeadStage          = 'inquiry' | 'consultation' | 'documents' | 'application' | 'decision' | 'enrolled'
export type LeadStatus         = 'active'  | 'stalled'     | 'completed' | 'dropped'
export type DocumentStatus     = 'pending' | 'approved'    | 'rejected'
export type NotificationType   = 'lead_assigned' | 'lead_stalled' | 'stall_resolved' | 'lead_reassigned' | 'stage_advanced' | 'document_reviewed' | 'admin_message' | 'team_update'

// ---------------------------------------------------------------------------
// Row types — one interface per table, columns match schema exactly
// ---------------------------------------------------------------------------

export interface Profile {
  id:                 string
  role:               UserRole
  full_name:          string        // NOT NULL in schema
  email:              string        // NOT NULL UNIQUE in schema
  phone:              string | null
  max_lead_capacity:  number | null // NULL = unlimited
  is_accepting_leads: boolean
  created_at:         string
  // no updated_at — not in schema
}

export interface University {
  id:         string
  name:       string
  country:    string
  // no city — not in schema
  created_at: string
  // no updated_at — not in schema
}

export interface Program {
  id:            string
  university_id: string
  name:          string
  degree_level:  string | null  // nullable TEXT, named degree_level
  // no degree_type, field_of_study, updated_at — not in schema
  created_at:    string
}

export interface Lead {
  id:               string
  reference_code:   string        // NOT NULL UNIQUE, generated by trigger
  student_id:       string
  consultant_id:    string | null // always consultant_id, never assigned_consultant_id
  program_id:       string
  stage:            LeadStage
  status:           LeadStatus   // stalled is a status value, not a boolean column
  stage_entered_at: string       // set by trigger on stage change only — NOT updated_at
  notes:            string | null
  created_at:       string
  updated_at:       string
}

export interface PipelineStageLabel {
  stage:                    LeadStage
  label:                    string
  sort_order:               number   // 1–6, determines display order
  stall_threshold_hours:    number
  escalation_threshold_hours: number  // Hours after stall_threshold to escalate
  severity_level:           string   // CRITICAL | HIGH | MEDIUM | NONE
}

export interface Document {
  id:               string
  lead_id:          string
  uploaded_by:      string
  file_url:         string
  file_name:        string      // NOT NULL
  status:           DocumentStatus
  rejection_reason: string | null
  created_at:       string
}

export interface ActivityLog {
  id:         string
  lead_id:    string
  actor_id:   string | null  // nullable — SECURITY DEFINER triggers have no auth.uid()
  type:       string
  content:    string | null  // nullable
  created_at: string
}

export interface CommunicationLog {
  id:         string
  lead_id:    string
  actor_id:   string
  channel:    'call' | 'email' | 'whatsapp' | 'in_person'  // CHECK constraint in schema
  summary:    string
  created_at: string
}

export interface Notification {
  id:         string
  user_id:    string
  type:       NotificationType
  content:    string
  is_read:    boolean
  created_at: string
}

export interface WebhookDedup {
  id:              string
  idempotency_key: string  // NOT NULL UNIQUE — named idempotency_key, not event_id
  created_at:      string
}

// ---------------------------------------------------------------------------
// Supabase Database shape (used with createClient<Database>())
// ---------------------------------------------------------------------------

export interface Database {
  __InternalSupabase: {
    PostgrestVersion: '12'
  }
  public: {
    Tables: {
      profiles: {
        Row:    Profile
        Insert: Omit<Profile, 'created_at'> & Partial<Pick<Profile, 'created_at'>>
        Update: Partial<Omit<Profile, 'id'>>
        Relationships: []
      }
      universities: {
        Row:    University
        Insert: Omit<University, 'id' | 'created_at'> & Partial<Pick<University, 'id' | 'created_at'>>
        Update: Partial<Omit<University, 'id'>>
        Relationships: []
      }
      programs: {
        Row:    Program
        Insert: Omit<Program, 'id' | 'created_at'> & Partial<Pick<Program, 'id' | 'created_at'>>
        Update: Partial<Omit<Program, 'id'>>
        Relationships: []
      }
      leads: {
        Row:    Lead
        // reference_code is generated by trigger — omit from Insert
        Insert: Omit<Lead, 'id' | 'reference_code' | 'stage_entered_at' | 'created_at' | 'updated_at'>
                & Partial<Pick<Lead, 'id' | 'stage_entered_at' | 'created_at' | 'updated_at'>>
        Update: Partial<Omit<Lead, 'id' | 'reference_code'>>
        Relationships: []
      }
      pipeline_stage_labels: {
        Row:    PipelineStageLabel
        Insert: PipelineStageLabel
        Update: Partial<PipelineStageLabel>
        Relationships: []
      }
      documents: {
        Row:    Document
        Insert: Omit<Document, 'id' | 'created_at'> & Partial<Pick<Document, 'id' | 'created_at'>>
        Update: Partial<Omit<Document, 'id'>>
        Relationships: []
      }
      activity_logs: {
        Row:    ActivityLog
        Insert: Omit<ActivityLog, 'id' | 'created_at'> & Partial<Pick<ActivityLog, 'id' | 'created_at'>>
        Update: Record<string, never>
        Relationships: []
      }
      communication_logs: {
        Row:    CommunicationLog
        Insert: Omit<CommunicationLog, 'id' | 'created_at'> & Partial<Pick<CommunicationLog, 'id' | 'created_at'>>
        Update: Record<string, never>
        Relationships: []
      }
      notifications: {
        Row:    Notification
        Insert: Omit<Notification, 'id' | 'created_at'> & Partial<Pick<Notification, 'id' | 'created_at'>>
        Update: Pick<Notification, 'is_read'>
        Relationships: []
      }
      webhook_dedup: {
        Row:    WebhookDedup
        Insert: Omit<WebhookDedup, 'id' | 'created_at'> & Partial<Pick<WebhookDedup, 'id' | 'created_at'>>
        Update: Record<string, never>
        Relationships: []
      }
    }
    Views: Record<string, {
      Row: Record<string, unknown>
      Relationships: []
    }>
    Functions: Record<string, {
      Args:    Record<string, unknown>
      Returns: unknown
    }>
    Enums: {
      user_role:          UserRole
      lead_stage:         LeadStage
      lead_status:        LeadStatus
      document_status:    DocumentStatus
      notification_type:  NotificationType
    }
  }
}
