/**
 * Zod schemas for Phase 3 validation.
 * Validates both lookup form and document upload.
 */

import { z } from 'zod'

/**
 * Reference code format: 8 uppercase alphanumeric characters
 * Generated by DB trigger, so we enforce the exact format here.
 */
const ReferenceCodeSchema = z
  .string()
  .length(8)
  .regex(
    /^[A-Z0-9]+$/,
    'Reference code must be 8 uppercase letters or numbers'
  )

/**
 * Email validation — use Zod's built-in email validator
 */
const EmailSchema = z
  .string()
  .email('Please enter a valid email address')
  .toLowerCase()

/**
 * Lookup form validation
 */
export const LookupFormSchema = z.object({
  reference_code: ReferenceCodeSchema,
  email: EmailSchema,
})

export type LookupFormInput = z.infer<typeof LookupFormSchema>

/**
 * File upload validation
 * Note: MIME type check happens on File object, which may not be reliable.
 * We validate by file extension as secondary check.
 */
const AllowedMimeTypes = [
  'application/pdf',
  'image/jpeg',
  'image/png',
]

const AllowedExtensions = ['.pdf', '.jpg', '.jpeg', '.png']

export const UploadFileSchema = z
  .instanceof(File)
  .refine(
    (file) => AllowedMimeTypes.includes(file.type),
    'Only PDF, JPG, and PNG files are accepted'
  )
  .refine(
    (file) => {
      const ext = `.${file.name.split('.').pop()?.toLowerCase()}`
      return AllowedExtensions.includes(ext)
    },
    'File extension must be .pdf, .jpg, .jpeg, or .png'
  )
  .refine(
    (file) => file.size <= 10 * 1024 * 1024,
    'File must be 10MB or smaller'
  )

export type ValidatedFile = z.infer<typeof UploadFileSchema>

/**
 * Document upload form validation
 */
export const DocumentUploadFormSchema = z.object({
  lead_id: z.string().uuid('Invalid lead ID'),
  student_id: z.string().uuid('Invalid student ID'),
  file: UploadFileSchema,
})

export type DocumentUploadFormInput = z.infer<typeof DocumentUploadFormSchema>

/**
 * Helper to safely parse FormData using Zod
 */
export function parseLookupFormData(formData: FormData) {
  return LookupFormSchema.safeParse({
    reference_code: (formData.get('reference_code') as string ?? '').trim().toUpperCase(),
    email: (formData.get('email') as string ?? '').trim().toLowerCase(),
  })
}

export function parseUploadFormData(formData: FormData) {
  return DocumentUploadFormSchema.safeParse({
    lead_id: (formData.get('lead_id') as string ?? '').trim(),
    student_id: (formData.get('student_id') as string ?? '').trim(),
    file: formData.get('file') as File,
  })
}
